[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "2uV52wYzEVMSHmENiwKFdYnmvxcxrjzXBKNgEWxJAyMm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ch/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
